Repository scenerygraphics/scenery, pull requests merged in 2022-11, with the labels that each got.

#497 Volume: Let currentTimepoint return the correct value
  src/main/kotlin/graphics/scenery/volumes/BufferedVolume.kt
  src/main/kotlin/graphics/scenery/volumes/Volume.kt
Labels: bugfix

#500 TransferFunction.serialize() fix endianess for stale return
  src/main/kotlin/graphics/scenery/volumes/TransferFunction.kt
Labels: bugfix

#498 Ray casting fix
  src/main/kotlin/graphics/scenery/Camera.kt
  src/test/kotlin/graphics/scenery/tests/unit/CameraTests.kt
Labels: bugfix

#496 Volume: Unify composeModel() routines, remove RAIVolumeSpatial
  src/main/kotlin/graphics/scenery/volumes/RAIVolume.kt
  src/main/kotlin/graphics/scenery/volumes/Volume.kt
  src/main/resources/graphics/scenery/repl/startup.py
  src/test/kotlin/graphics/scenery/tests/examples/volumes/ProceduralVolumeExample.kt
Labels: bugfix

#501 DefaultSpatial: worldPosition with a null argument and a non scene parent now does not apply the position twice to the return value.
  src/main/kotlin/graphics/scenery/attribute/spatial/DefaultSpatial.kt
Labels: bugfix

#494 VR UI improvements
  src/main/kotlin/graphics/scenery/backends/Display.kt
  src/main/kotlin/graphics/scenery/controls/Hololens.kt
  src/main/kotlin/graphics/scenery/controls/OpenVRHMD.kt
  src/main/kotlin/graphics/scenery/controls/TrackedStereoGlasses.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/Enablable.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/VRGrab.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/VRPress.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/VRScale.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/VRSelect.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/VRSelectionWheel.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/VRTouch.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/VRTreeSelectionWheel.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/VRTwoHandDragBehavior.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/WheelAction.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/WheelEntry.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/WheelMenu.kt
  src/main/kotlin/graphics/scenery/primitives/LineBetweenNodes.kt
  src/test/kotlin/graphics/scenery/tests/examples/advanced/VRControllerExample.kt
Labels: enhancement

#502 Gitlab CI: Stabilise Argos results by using scenery.RandomSeed property
  .gitlab-ci.yml
Labels: bugfix, build-system

#488 Image.kt changed bufferImageToRGBABuffer imageBuffer allocation to us…
  src/main/kotlin/graphics/scenery/utils/Image.kt
Labels: bugfix
