Repository scenerygraphics/scenery, pull requests merged in 2023-06, with the labels that each got.

#539 Deprecate OpenGL renderer
  src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
Labels: enhancement, dresden-hackathon-2023

#541 Remove the OpenGL renderer
  build.gradle.kts
  src/main/kotlin/graphics/scenery/DetachedHeadCamera.kt
  src/main/kotlin/graphics/scenery/SceneryBase.kt
  src/main/kotlin/graphics/scenery/backends/Renderer.kt
  src/main/kotlin/graphics/scenery/backends/SceneryWindow.kt
  src/main/kotlin/graphics/scenery/backends/UBO.kt
  src/main/kotlin/graphics/scenery/backends/opengl/OpenGLObjectState.kt
  src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderer.kt
  src/main/kotlin/graphics/scenery/backends/opengl/OpenGLRenderpass.kt
  src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderModule.kt
  src/main/kotlin/graphics/scenery/backends/opengl/OpenGLShaderProgram.kt
  src/main/kotlin/graphics/scenery/backends/opengl/OpenGLUBO.kt
  src/main/kotlin/graphics/scenery/backends/vulkan/OpenGLSwapchain.kt
  src/main/kotlin/graphics/scenery/controls/GLFWMouseAndKeyHandler.kt
  src/main/kotlin/graphics/scenery/controls/InputHandler.kt
  src/main/kotlin/graphics/scenery/controls/JOGLMouseAndKeyHandler.kt
  src/main/kotlin/graphics/scenery/controls/SwingMouseAndKeyHandler.kt
  src/main/kotlin/graphics/scenery/controls/behaviours/RollingBallCameraControl.kt
  src/main/kotlin/graphics/scenery/numerics/Random.kt
  src/main/kotlin/graphics/scenery/repl/REPL.kt
  src/main/kotlin/graphics/scenery/textures/Texture.kt
  src/main/kotlin/graphics/scenery/utils/Image.kt
  src/main/kotlin/graphics/scenery/utils/SceneryJPanel.kt
  src/main/kotlin/graphics/scenery/utils/TGAReader.kt
  src/main/kotlin/graphics/scenery/utils/extensions/Numbers.kt
  src/test/kotlin/graphics/scenery/tests/examples/volumes/StackedVolumesExample.kt
  src/test/kotlin/graphics/scenery/tests/unit/controls/GLFWMouseAndKeyHandlerTests.kt
  src/test/kotlin/graphics/scenery/tests/unit/controls/JOGLMouseAndKeyHandlerTests.kt
  src/test/kotlin/graphics/scenery/tests/unit/controls/SwingMouseAndKeyHandlerTests.kt
Labels: enhancement

#557 TransferFunctionEditor: change from JFrame to JPanel
  src/main/kotlin/graphics/scenery/volumes/TransferFunctionEditor.kt
  src/test/kotlin/graphics/scenery/tests/examples/volumes/TransferFunctionEditorExample.kt
Labels: dd-hackathon-2023

#568 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement, build-system

#564 Cylinder: Add top and bottom lids, make smooth shading optional
  src/main/kotlin/graphics/scenery/primitives/Cylinder.kt
  src/test/kotlin/graphics/scenery/tests/unit/VolumeMeasuererTests.kt
Labels: enhancement
