Repository scenerygraphics/scenery, pull requests merged in 2024-04, with the labels that each got.

#717 Reorganise VDI classes and mark their APIs as `@Experimental`
  src/main/kotlin/graphics/scenery/utils/extensions/TextureUtils.kt
  src/main/kotlin/graphics/scenery/volumes/vdi/VDIData.kt
  src/main/kotlin/graphics/scenery/volumes/vdi/VDIDataIO.kt
  src/main/kotlin/graphics/scenery/volumes/vdi/VDINode.kt
  src/main/kotlin/graphics/scenery/volumes/vdi/VDIStreamer.kt
  src/main/kotlin/graphics/scenery/volumes/vdi/VDIVolumeManager.kt
  src/main/resources/graphics/scenery/volumes/VolumeRenderer.cl
  src/main/resources/graphics/scenery/volumes/vdi/AccumulateVDI.comp
  src/main/resources/graphics/scenery/volumes/vdi/GridCellsToZero.comp
  src/main/resources/graphics/scenery/volumes/vdi/VDIGenerator.comp
  src/test/java/graphics/scenery/tests/applications/vdi/ServerApplication.kt
  src/test/java/graphics/scenery/tests/applications/vdi/VDIStreamingExample.kt
  src/test/kotlin/graphics/scenery/tests/examples/volumes/VolumeManagerSwitchingExample.kt
Labels: enhancement, documentation

#721 Fix missing Xlib struct, fix query pool stride
  build-example-project.sh
  build.gradle.kts
  buildSrc/src/main/kotlin/scenery/utils.kt
  gradle.properties
  settings.gradle.kts
  src/main/kotlin/graphics/scenery/backends/vulkan/VulkanCommandBuffer.kt
Labels: enhancement, bugfix

#707 Make atmosphere shader compatible with sciview inspector
  src/main/kotlin/graphics/scenery/primitives/Atmosphere.kt
  src/main/resources/graphics/scenery/backends/shaders/Atmosphere.frag
  src/test/kotlin/graphics/scenery/tests/examples/basic/AtmosphereExample.kt
Labels: enhancement

#739 Clean up Node state variables and Node interface
  src/main/kotlin/graphics/scenery/Camera.kt
  src/main/kotlin/graphics/scenery/DefaultNode.kt
  src/main/kotlin/graphics/scenery/DetachedHeadCamera.kt
  src/main/kotlin/graphics/scenery/DirectionalLight.kt
  src/main/kotlin/graphics/scenery/InstancedNode.kt
  src/main/kotlin/graphics/scenery/Mesh.kt
  src/main/kotlin/graphics/scenery/Node.kt
  src/main/kotlin/graphics/scenery/PointLight.kt
  src/main/kotlin/graphics/scenery/RichNode.kt
  src/main/kotlin/graphics/scenery/atomicsimulations/AtomicSimulation.kt
  src/main/kotlin/graphics/scenery/backends/RendererFlags.kt
  src/main/kotlin/graphics/scenery/backends/vulkan/VulkanNodeHelpers.kt
  src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRenderer.kt
  src/main/kotlin/graphics/scenery/backends/vulkan/VulkanRendererMetadata.kt
  src/main/kotlin/graphics/scenery/backends/vulkan/VulkanScenePass.kt
  src/main/kotlin/graphics/scenery/primitives/PointCloud.kt
Labels: enhancement

#742 ComputeHistogram.comp: Fix 16 bit histogram calculation on gpu
  src/main/resources/graphics/scenery/volumes/ComputeHistogram.comp
Labels: prague-hackathon-2024
